import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import * as publicOpportunityApi from '../api/publicOpportunityApi'
import type { PublicOpportunityResponse, WorkMode } from '../types'
import { EmptyState, ErrorState, FilterBar, InternshipCard, LoadingState, Pagination, SearchInput, Select, VerifiedBadge } from '../../../components/ui'

const workModes:WorkMode[]=['ONSITE','HYBRID','REMOTE']
export function PublicOpportunityListPage(){const {t,i18n}=useTranslation();const [params]=useSearchParams();const organization=params.get('organization')??undefined;const [query,setQuery]=useState('');const [location,setLocation]=useState('');const [workMode,setWorkMode]=useState<WorkMode|''>('');const [page,setPage]=useState(0);const result=useQuery({queryKey:['public-opportunities',query,location,workMode,organization,page],queryFn:()=>publicOpportunityApi.listPublicOpportunities({query:query||undefined,location:location||undefined,workMode:workMode||undefined,organization,page,size:12})});return <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 sm:py-16"><header><h1 className="font-display text-4xl font-extrabold tracking-tight text-brand-navy dark:text-foreground sm:text-6xl">{t('opportunities:public.title')}</h1><p className="mt-4 max-w-xl text-lg leading-8 text-foreground-secondary">{t('opportunities:public.subtitle')}</p></header><FilterBar className="mt-8" search={<SearchInput label={t('opportunities:public.searchLabel')} placeholder={t('opportunities:public.searchPlaceholder')} value={query} onChange={event=>{setQuery(event.target.value);setPage(0)}}/>}><SearchInput label={t('opportunities:public.locationLabel')} placeholder={t('opportunities:public.locationPlaceholder')} value={location} onChange={event=>{setLocation(event.target.value);setPage(0)}} className="sm:w-48"/><Select aria-label={t('opportunities:public.workModeLabel')} value={workMode} onChange={event=>{setWorkMode(event.target.value as WorkMode|'');setPage(0)}} className="sm:w-48"><option value="">{t('opportunities:public.allWorkModes')}</option>{workModes.map(value=><option key={value} value={value}>{t(`opportunities:workModeValues.${value}`)}</option>)}</Select></FilterBar><div className="mt-8">{result.isLoading?<LoadingState label={t('opportunities:public.loading')}/>:result.isError?<ErrorState description={t('opportunities:public.error')} onRetry={()=>void result.refetch()}/>:result.data?.content.length===0?<EmptyState title={t('opportunities:public.empty')}/>:<ul className="grid gap-4">{result.data?.content.map(item=><li key={item.id}><OpportunityCard opportunity={item} locale={i18n.resolvedLanguage??'en'} t={t}/></li>)}</ul>}</div>{result.data&&<Pagination page={result.data.page} totalPages={result.data.totalPages} onPageChange={setPage} className="mt-10"/>}</div>}

function OpportunityCard({opportunity,locale,t}:{opportunity:PublicOpportunityResponse;locale:string;t:ReturnType<typeof useTranslation>['t']}){const duration=Math.max(1,Math.round((new Date(opportunity.endDate).getTime()-new Date(opportunity.startDate).getTime())/(1000*60*60*24*30)));return <InternshipCard title={opportunity.title} organization={opportunity.organization.name} location={opportunity.location??undefined} workMode={t(`opportunities:workModeValues.${opportunity.workMode}`)} duration={t('opportunities:public.durationMonths',{count:duration})} deadline={opportunity.applicationDeadline?t('opportunities:public.applyBy',{date:new Intl.DateTimeFormat(locale==='so'?'so-SO':'en',{dateStyle:'medium'}).format(new Date(opportunity.applicationDeadline))}):undefined} actions={<Link to={`/opportunities/${opportunity.id}`} className="rounded-md border border-brand-primary px-4 py-2 text-sm font-semibold text-brand-primary hover:bg-brand-blue-soft dark:border-info dark:text-info dark:hover:bg-info-bg">{t('opportunities:public.viewDetails')}</Link>}><p className="line-clamp-2">{opportunity.description}</p>{opportunity.organization.verified&&<div className="mt-2"><VerifiedBadge/></div>}</InternshipCard>}
