import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import * as publicOpportunityApi from '../../opportunities/api/publicOpportunityApi'
import type { OrganizationType, OrganizationSummaryResponse } from '../types'
import { EmptyState, EntityCard, ErrorState, LoadingState, SearchInput, Select, VerifiedBadge } from '../../../components/ui'

const types: OrganizationType[]=['COMPANY','NGO','GOVERNMENT','OTHER']
export function PublicOrganizationListPage(){const {t}=useTranslation();const [query,setQuery]=useState('');const [type,setType]=useState<OrganizationType|''>('');const result=useQuery({queryKey:['public-organization-directory'],queryFn:()=>publicOpportunityApi.listPublicOpportunities({size:50,page:0})});const organizations=useMemo(()=>{const map=new Map<string,OrganizationSummaryResponse>();for(const opportunity of result.data?.content??[])map.set(opportunity.organization.id,opportunity.organization);const normalizedQuery=query.trim().toLocaleLowerCase();return [...map.values()].filter(item=>(!normalizedQuery||item.name.toLocaleLowerCase().includes(normalizedQuery))&&(!type||item.type===type))},[query,result.data,type]);return <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 sm:py-16"><header><h1 className="font-display text-4xl font-extrabold tracking-tight text-brand-navy dark:text-foreground sm:text-6xl">{t('common:publicPages.organizations.title')}</h1><p className="mt-4 max-w-xl text-lg leading-8 text-foreground-secondary">{t('common:publicPages.organizations.subtitle')}</p></header><div className="mt-8 grid gap-3 sm:grid-cols-[1fr_14rem]"><SearchInput label={t('common:publicPages.organizations.searchLabel')} placeholder={t('common:publicPages.organizations.search')} value={query} onChange={event=>setQuery(event.target.value)}/><Select aria-label={t('common:publicPages.organizations.typeLabel')} value={type} onChange={event=>setType(event.target.value as OrganizationType|'')}><option value="">{t('common:publicPages.organizations.allTypes')}</option>{types.map(value=><option key={value} value={value}>{t(`organization:typeValues.${value}`)}</option>)}</Select></div><div className="mt-8">{result.isLoading?<LoadingState label={t('common:publicPages.organizations.loading')}/>:result.isError?<ErrorState description={t('common:publicPages.organizations.error')} onRetry={()=>void result.refetch()}/>:organizations.length===0?<EmptyState title={t('common:publicPages.organizations.empty')}/>:<div className="grid gap-4">{organizations.map(org=><EntityCard key={org.id} name={org.name} subtitle={t(`organization:typeValues.${org.type}`)} meta={org.verified?<VerifiedBadge/>:undefined} actions={<Link to={`/organizations/${org.id}`} className="shrink-0 rounded-md border border-brand-primary px-4 py-2 text-sm font-semibold text-brand-primary hover:bg-brand-blue-soft dark:border-info dark:text-info dark:hover:bg-info-bg">{t('common:publicPages.organizations.view')}</Link>}/>)}</div>}</div><p className="mt-5 text-sm text-muted">{t('common:publicPages.organizations.scopeNote')}</p></div>}
